### ISSUE TITLE
Submits empty value if the user enters the placeholder text

### ISSUE THREAD

**Issue by jaikdean** [danbentley/placeholder#4]
If you have the following input:

``` html
<input type="text" name="foo" placeholder="bar" />
```

and the user enters `bar` into it (eg. the same as the placeholder text), the script will clear this before the form is submitted and send an empty value.

I've written a placeholder script for MooTools which covers this by doing a check in the onBlur event. Each input has a flag that gets set in the onBlur event if the value is not empty. Only inputs without the flag set get reset before the form submission.

**Comment by danbentley** [comment]
Hi jaikdean,

Yeah, this issue has been bugging me. 

I've created a branch with a quick fix. We set a flag against an element in the "change" event handler. We then look for the flag if a "focus" event has been triggered or the form has been submitted.

https://github.com/danbentley/placeholder/blob/clearinputs/js/jquery.placeholder.js

**Comment by danbentley** [comment]
This is now fixed in the latest version.
