### ISSUE TITLE
Fields with preset values are not cleared on blur

### ISSUE THREAD

**Issue by scarlac** [danbentley/placeholder#5]
If a field has a value when the page loads, then entering the field, clearing the content and exiting, causes the placeholder text to stick as the new value. This is due to the fact that the "changed" flag indicates true for fields that are initialized with a value in combination with onblur just checking for changed flag, and not actual value.

The error can be reproduced in Firefox 3.6 with your own demo code.
- Seph

**Comment by scarlac** [comment]
I forked the code and made a fix. I also included jQuery 1.3 support in the fix. You can merge it in if you'd like. Also, I added a minified version in the build/ folder using jscompress.com.

**Comment by danbentley** [comment]
Hi scarlac,

Nice spot!

I've noticed you add a class on the input if a placeholder value is being displayed, I'd like to hold off on this for now. Myself and CSSWizardry have been working on doing something with classes for a while now. I'll merge in the first commit on your fork.

It should be all merged in as your read this.

Thanks for the fix!
